# version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015
platform: Any CPU
configuration: Release
skip_tags: true

init:
  - choco install -y erlang
  - choco install -y rabbitmq

before_build:
  - copy "Local.props.example" "Local.props"
  - ps: |
      $localpropsitem = Get-ChildItem ".\Local.props"
      $xml = New-Object -TypeName XML
      $xml.Load($localpropsitem)
      $xml.Project.PropertyGroup.PropAssemblyVersion = ${env:APPVEYOR_BUILD_VERSION}
      $xml.Save($localpropsitem)

build:
  parallel: false
  project: RabbitMQDotNetClient.sln
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false
  verbosity: minimal

after_build:
  - ps: |
      $semver = ${env:APPVEYOR_BUILD_VERSION} -ireplace '(\d+.\d+.\d+).(\d+)', "`$1-ci`$2-${env:APPVEYOR_REPO_BRANCH}"
      $semver = $semver.Substring(0, [System.Math]::Min(20, $semver.Length))
      nuget pack RabbitMQ.Client.nuspec -version $semver -symbols
      nuget pack RabbitMQ.ServiceModel.nuspec -version $semver -symbols

install:
  - ps: |
      $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RabbitMQ"
      if (Test-Path "HKLM:\SOFTWARE\Wow6432Node\") { $regPath = "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\RabbitMQ" }
      $path = Split-Path -Parent (Get-ItemProperty $regPath "UninstallString").UninstallString
      $version = (Get-ItemProperty $regPath "DisplayVersion").DisplayVersion
      [Environment]::SetEnvironmentVariable("RABBITMQ_HOME", "$path\rabbitmq_server-$version", "Machine")
      $env:RABBITMQ_HOME = "$path\rabbitmq_server-$version"
      [Environment]::SetEnvironmentVariable("RABBITMQ_RABBITMQCTL_PATH", "$path\rabbitmq_server-$version\sbin\rabbitmqctl.bat", "Machine")
      $env:RABBITMQ_RABBITMQCTL_PATH = "$path\rabbitmq_server-$version\sbin\rabbitmqctl.bat"

test:
  assemblies:
    - '**\build\bin\unit-tests.dll'
  categories:
    except:
      - RequireSMP

artifacts:
  - path: '**\*.nupkg'

deploy: off
