# version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015
platform: Any CPU
configuration: Release
skip_tags: true

init:
  - choco install -y erlang
  - choco install -y rabbitmq

before_build:
  - copy "Local.props.example" "Local.props"
  - ps: |
      $localpropsitem = Get-ChildItem ".\Local.props"
      $xml = New-Object -TypeName XML
      $xml.Load($localpropsitem)
      $xml.Project.PropertyGroup.PropAssemblyVersion = ${env:APPVEYOR_BUILD_VERSION}
      $xml.Save($localpropsitem)

build:
  parallel: false
  project: RabbitMQDotNetClient.sln
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false
  verbosity: minimal

before_test:
  - ps: |
      $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RabbitMQ"
      if (Test-Path "HKLM:\SOFTWARE\Wow6432Node\") { $regPath = "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\RabbitMQ" }
      $path = Split-Path -Parent (Get-ItemProperty $regPath "UninstallString").UninstallString
      $version = (Get-ItemProperty $regPath "DisplayVersion").DisplayVersion
      [Environment]::SetEnvironmentVariable("RABBITMQ_HOME", "$path\rabbitmq_server-$version", "User")
      [Environment]::SetEnvironmentVariable("RABBITMQ_RABBITMQCTL_PATH", "$path\rabbitmq_server-$version\sbin\rabbitmqctl.bat", "User")

test_script:
  - cd c:\projects\rabbitmq-dotnet-client
  - tools\nunit\bin\nunit-console.exe /framework:net-4.5 -config=Debug projects/client/Unit/RabbitMQ.Client.Unit.csproj

test: off
deploy: off
