# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2
platform: Any CPU
configuration: Release
skip_tags: true

init:
  - choco install -y erlang
  - choco install -y rabbitmq

build:
  parallel: true
  project: RabbitMQDotNetClient.sln
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false
  verbosity: normal

test_script:
  - cd c:\projects\rabbitmq-dotnet-client
  - tools\nunit\bin\nunit-console.exe /framework:net-4.5 -config=Debug projects/client/Unit/RabbitMQ.Client.Unit.csproj

test: off
deploy: off
